/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOperacoesRouteImport } from './routes/_authenticated/operacoes'
import { Route as AuthenticatedParcelasRouteImport } from './routes/_authenticated/parcelas'
import { Route as AuthenticatedOperacoesIdRouteImport } from './routes/_authenticated/operacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacoesRoute = AuthenticatedOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParcelasRoute = AuthenticatedParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacoesIdRoute =
  AuthenticatedOperacoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOperacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/operacoes': typeof AuthenticatedOperacoesRouteWithChildren
  '/parcelas': typeof AuthenticatedParcelasRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/operacoes': typeof AuthenticatedOperacoesRouteWithChildren
  '/parcelas': typeof AuthenticatedParcelasRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/operacoes': typeof AuthenticatedOperacoesRouteWithChildren
  '/_authenticated/parcelas': typeof AuthenticatedParcelasRoute
  '/_authenticated/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/dashboard' | '/operacoes' | '/parcelas' | '/operacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/dashboard' | '/operacoes' | '/parcelas' | '/operacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/operacoes'
    | '/_authenticated/parcelas'
    | '/_authenticated/operacoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacoes': {
      id: '/_authenticated/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AuthenticatedOperacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcelas': {
      id: '/_authenticated/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof AuthenticatedParcelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacoes/$id': {
      id: '/_authenticated/operacoes/$id'
      path: '/$id'
      fullPath: '/operacoes/$id'
      preLoaderRoute: typeof AuthenticatedOperacoesIdRouteImport
      parentRoute: typeof AuthenticatedOperacoesRoute
    }
  }
}

interface AuthenticatedOperacoesRouteChildren {
  AuthenticatedOperacoesIdRoute: typeof AuthenticatedOperacoesIdRoute
}

const AuthenticatedOperacoesRouteChildren: AuthenticatedOperacoesRouteChildren =
  {
    AuthenticatedOperacoesIdRoute: AuthenticatedOperacoesIdRoute,
  }

const AuthenticatedOperacoesRouteWithChildren =
  AuthenticatedOperacoesRoute._addFileChildren(
    AuthenticatedOperacoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOperacoesRoute: typeof AuthenticatedOperacoesRouteWithChildren
  AuthenticatedParcelasRoute: typeof AuthenticatedParcelasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOperacoesRoute: AuthenticatedOperacoesRouteWithChildren,
  AuthenticatedParcelasRoute: AuthenticatedParcelasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
